# Generated by Django 5.1.8 on 2025-04-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="from_address",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
