# Generated by Django 5.1.8 on 2025-04-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contactpage_from_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("singleline", "Single line text"),
                    ("multiline", "Multi-line text"),
                    ("email", "Email"),
                    ("url", "URL"),
                    ("number", "Number"),
                ],
                max_length=16,
                verbose_name="Field Type",
            ),
        ),
    ]
