# Generated by Django 5.1.8 on 2025-04-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_background_image",
            field=models.ForeignKey(
                help_text="배너 배경 이미지",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button",
            field=models.ForeignKey(
                blank=True,
                help_text="옵션선택",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button_text",
            field=models.CharField(
                default="Read More", help_text="Button text", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="lead_text",
            field=models.CharField(
                blank=True, help_text="Text to describe the page", max_length=255
            ),
        ),
    ]
