# Generated by Django 5.1.8 on 2025-04-14 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_banner_background_image_homepage_button_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="banner_background_image",
            field=models.ForeignKey(
                help_text="배너 배경 이미지",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="버튼 배경이미지",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="lead_text",
            field=models.CharField(
                blank=True,
                help_text="Text to describe the page",
                max_length=255,
                verbose_name="소개글",
            ),
        ),
    ]
