# Generated by Django 5.1.8 on 2025-04-14 22:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_homepage_banner_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("title", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text to display", "required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                },
                null=True,
            ),
        ),
    ]
