# Generated by Django 5.1.8 on 2025-04-14 23:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("title", 1), ("cards", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text to display", "required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    3: ("wagtail.blocks.TextBlock", (), {"max_length": 234}),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("text", 3), ("image", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: ("wagtail.blocks.StructBlock", [[("cards", 6)]], {}),
                },
                null=True,
            ),
        ),
    ]
