# Generated by Django 5.1.8 on 2025-04-24 22:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flex", "0002_flexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("title", 1),
                    ("cards", 11),
                    ("image_and_text", 16),
                    ("cta", 18),
                    ("testimonial", 19),
                    ("pricing_table", 20),
                    ("richtext", 21),
                    ("large_image", 22),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text to display", "required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    3: ("wagtail.blocks.TextBlock", (), {"max_length": 234}),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "More details", "max_length": 100},
                    ),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_text", 5),
                                ("internal_page", 6),
                                ("external_link", 7),
                            ]
                        ],
                        {"help_text": "내부 또는 외부 링크 선택"},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("text", 3), ("image", 4), ("link", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: ("wagtail.blocks.StructBlock", [[("cards", 10)]], {}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("right", "Right")]},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "...", "max_length": 60},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 140, "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_text", 5),
                                ("internal_page", 6),
                                ("external_link", 7),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 4),
                                ("image_alignment", 12),
                                ("title", 13),
                                ("text", 14),
                                ("link", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Max length of 200 characters.",
                            "max_length": 200,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 17), ("link", 15)]],
                        {},
                    ),
                    19: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (),
                        {
                            "target_model": "testimonials.Testimonial",
                            "template": "streams/testimonial_block.html",
                        },
                    ),
                    20: (
                        "streams.blocks.PricingTableBlock",
                        (),
                        {
                            "table_options": {
                                "autoColumnSize": False,
                                "colHeaders": False,
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                ],
                                "editor": "text",
                                "minSpareRows": 0,
                                "renderer": "text",
                                "rowHeaders": True,
                                "startCols": 4,
                                "startRows": 4,
                                "stretchH": "all",
                            }
                        },
                    ),
                    21: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h1",
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                            ],
                            "template": "streams/simple_richtext_block.html",
                        },
                    ),
                    22: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "crop imagesize to 1200x775",
                            "icon": "image",
                            "template": "streams/large_image_block.html",
                        },
                    ),
                },
                null=True,
            ),
        ),
    ]
